### ISSUE TITLE
Make second order creation conditional on packages loaded

### ISSUE THREAD

**Issue by Vaibhavdixit02** [SciML/OptimizationBase.jl#111]
As brought up on Slack it's unintuitive right now that ReverseDiff is used as inner and ForwardDiff as outer by default even when they are not loaded. That should be put behind a conditional and when not available FD over FD or RD over RD should be done, maybe with warning?

**Comment by ChrisRackauckas** [comment]
That would be very weird because Forward over Forward is very optimal and easier to be optimized for a given code. It would be unintuitive if you choose forward mode and you get any reverse mode at all: all forward is a good idea for many common cases, especially with a tape-based AD (since then it's only fast on scalars if you JIT compile the tape, which is not allowed for many use cases), and making that inaccessible is not very user friendly.
